config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root is the homepage
  # root is the page devise goes to after logging in
  root 'projects#new'

  get 'analytics/usage', to: 'analytics#usage'
  get 'community/home', to: 'community#home'
  get 'profile', to: 'profiles#show'
  get 'profile/:id', to: 'profiles#show'
  get 'profile/projects', to: 'profiles#load_project_previews'
  get 'analytics/project_location_csv'
  get 'analytics/project_runtimes'
  get 'analytics/users_created'
  get 'users/projects', to: 'users#projects'

  get 'users/projects', to: 'users#projects'
  get 'users/projects/:id', to: 'users#projects'
  get 'users/followers', to: 'users#followers'
  get 'users/following', to: 'users#followees'
  get '/users/newProject', to: 'users#newProjectButton'

  get 'users/index', to: 'users#index'
  get 'users/searchbar', to: 'users#searchbar'
  post 'users/search', to: 'users#search'
  post 'users/follow', to: 'users#follow'
  post 'users/unfollow', to: 'users#unfollow'

  post '/projects/:id/permissions/:visibility', to: 'projects#toggle'
  post '/projects/:id/run', to: 'projects#run'
  get '/projects/:id/progress', to: 'projects#progress'
  get '/projects/:id/cancel', to: 'projects#cancel'

  resources(:projects,  except: [:index]) do
    member do
      post 'receive_service_output', to: 'projects#receive_service_output'
      get 'fork', to: 'projects#fork'
      post '',  to: 'projects#create'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  # GET /profiles/show
  def show
    if params[:id].nil?
      @user = User.find(current_user.id)
      render :home
    else
      @user = User.find(params[:id])
      render :show
    end

  end

  def load_project_previews
      @user = User.find(params[:id])
      json_list = []
      projects = @user.projects
      projects.each do |project|
        json_list.append(project.to_json(:include => [:title, :id] ))
      end
  end
end

app/views/profiles/_followee.html.erb
<div class="col-xs-6 col-md-4 container-followee" id="followee-preview"<%= followee.id%>">
  <div class="card card-img-followee">
    <%= image_tag src=followee.avatar.url, :class => 'circular--square', :alt => 'Avatar' %>
    <div class="card-block">
      <div class="card-title">
        <strong><h1><%= followee.username %></h1></strong>
      </div>
    </div>
</div>

app/views/profiles/_follower.html.erb
<div class="col-xs-6 col-md-4 container-follower" id="follower-preview"<%= follower.id%>">
  <div class="card card-img-follower">
    <%= image_tag src=follower.avatar.url, :class => 'circular--square', :alt => 'Avatar' %>
    <div class="card-block">
      <div class="card-title">
        <strong><h1><%= follower.username %></h1></strong>
      </div>
  </div>

</div>

app/views/profiles/_peer_project.html.erb
<div id="project-<%= project.id%>">
  <div class="card card-project card-project-preview"  >
    <div class="col-sm-6">
      <div class="card-title">
        <strong>
          <h2>
            <%= project.title %>
          </h2>
        </strong>
      </div>
    </div>
    <div class="project_options" style="visibility: hidden;">
      <div class="col-sm-2" style="align-content: center;">
        <h2>
          <a href="<%= edit_project_path(project)%>">
            <div class="glyphicon glyphicon-folder-open"></div>
          </a>
        </h2>

        </a>
      </div>

      <div class="col-sm-2">
        <h2>
          <a href=""<%= edit_project_path(project)%>">
          <div class="glyphicon glyphicon-play" style="color: green;"></div>
          </a>
        </h2>

      </div>
      <div class="col-sm-2">
        <h2>
          <a href="#" onclick="forkProject(<%= project.id%>)">
            <div class="fa fa-code-fork"></button>
          </a>
        </h2>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_project.html.erb
<div id="project-preview-<%= project.id%>">
  <div class="card card-project card-project-preview"  >
    <div class="row">
      <div class="col-sm-4">
        <div class="card-title" style="text-overflow: ellipsis;">
          <h3>
            <strong>
              <%= project.title %>
            </strong>
          </h3>
        </div>
      </div>
      <div class="project_options" style="visibility: hidden;">
        <div class="col-sm-2" style="align-content: center;">
          <h3>
            <a href="<%= edit_project_path(project)%>">
              <div class="glyphicon glyphicon-folder-open"></div>
            </a>
          </h3>

        </div>

        <div class="col-sm-2">
          <h3>
            <a class="run_project" id="<%=project.id%>" href="#" onclick="onRunProject(<%=project.id%>)" >
              <div class="glyphicon glyphicon-play" style="color: green;" ></div>
            </a>
          </h3>

        </div>

        <div class="col-sm-2">
          <h3>
            <a  href="#" onclick="delete_project(<%= project.id %>)">
              <div class="glyphicon glyphicon-remove" style="color: red;"></div>
            </a>
          </h3>
        </div>

        <div class="col-sm-2">
          <h2>
            <a href="#" >
              <% if project.public %>
                  <i id="project-<%= project.id%>-visibility" class="fa fa-unlock-alt" onclick="makeProjectPrivate(<%=project.id %>)" style="color: black;"></i>
              <% else %>
                  <i id="project-<%= project.id%>-visibility" class="glyphicon glyphicon-lock" onclick="makeProjectPublic(<%=project.id %>)" aria-hidden="true"></i>
              <% end %>
            </a>
          </h2>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_running_project.html.erb
<div id="running-project-<%= project.id%>">
  <div class="card card-project card-project-preview"  >
    <div class="row">
      <div class="col-sm-12">
        <div class="card-title" style="text-overflow: ellipsis;">
          <h4>
            <strong>
              <%= project.title %>
            </strong>
          </h4>
        </div>
      </div>
      <div class= "col-sm-12">
        <strong> started at: <%= project.time_started %>
      </div>
    </div>
    <div id="status-<%= project.id%>" style="margin-left: 8px">
      <div class="progress"> 
        <div id="progress-<%= project.id%>" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">
        </div>
      </div>
    </div>
    <div class="card-footer" style="margin-left: 8px">
      <button onclick="return cancelProject(<%= project.id %>);" class="btn btn-warning cancel_project" id="cancel-<%= project.id%>" class="btn btn-danger"> Cancel </button>
    </div>
  </div>
</div>

app/views/profiles/home.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="col-md-3 no-float" style="padding-top: 15px; background-color: lightgrey">
	    <div class="profile-sidebar card">
		    <div class="center-box">	    
			    <%= image_tag @user.avatar.url(:thumb), :class => 'circular--square--large' %>
                    </div>
        <h2 style="color: #f3f3f3;"><%= @user.username %></h2>
        <h2 style="color: #f3f3f3;"><%= @user.email %></h2>

          <ul class="nav nav-pills nav-stacked" >
            <li role="presentation">
              <a href= "#" id="show_projects">
                <h4>My Projects</h4>
              </a>
            </li>
            <li role="presentation">
              <a href= "#" id="show_followers">
                <h4>Followers</h4>
              </a>
            </li>
            <li role="presentation">
              <a href= "#" id="show_following">
                <h4>Following</h4>
              </a>
            </li>
            <li role="presentation">
              <a href= "#" id="search_for_users">
                <h4>Search For Users</h4>
              </a>
            </li>
          </ul>
      </div>
    </div>

    <div class="col-md-6 no-float" id="preview-container" >
      <div class="no-float" id="search_container">
      </div>

      <h2 id="preview-header" class="panel-header" style="padding-left: 15px;" ><strong></strong></h2>
      <div id="preview-body" style="height: 100%; overflow-y: scroll; border-radius: 15px; padding: 15px;"></div>
    </div>
      <div class="col-md-3 no-float" style="background-color: lightgrey; text-align: center;">
        <h2 style="color: #333; position: fixed; margin-bottom: 2em; margin-left: 2.5em; "> Active Projects</h2>
        <div class="profile-active-projects">
          <div class="running_projects">
            <%= render partial: 'profiles/running_project', collection: @user.running_projects, as: 'project' %>
          </div>
        </div>

      </div>
  </div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="navbar-profile" class="col-md-3 no-float" style="padding-top: 15px;">
        <div class="col-lg-2">
          <div class="card" style="box-shadow: 5px 5px 5px 5px; align-content: center; width: 170px; background-color: white;">
            <%= image_tag @user.avatar.url(:thumb), :class => 'circular--square', :align => 'middle' %>
            <br/>
            <h2><strong> <%= @user.username %> </strong> </h2>
            <strong> Member Since <%= @user.created_at %>
            <strong> Last Sign In: <%= @user.last_sign_in_at.strftime("%m/%d/%Y") %>
          </div>
        </div>
	<div class="col-lg-6"> 
        <ul class="nav navbar-nav" >
          <li role="presentation">
	  <a href= "#" id="show_peer_projects" onclick= "displayPeerProjects(<%=@user.id %>)">
              <h4>Projects</h4>
            </a>
          </li>
          <li role="presentation">
            <a href= "#" id="show_peer_followers">
              <h4>Followers</h4>
            </a>
          </li>
          <li role="presentation">
            <a href= "#" id="show_peer_following">
              <h4>Following</h4>
            </a>
          </li>
        </ul>
        </div>


    </div>
      <div id="preview-container" class="col-md-6 no-float">
        <div class="no-float" id="search_container">
        </div>

        <h2 id="preview-header" class="panel-header" style="padding-left: 15px;" ><strong></strong></h2>
        <div id="preview-body" style="height: 400px; overflow-y: scroll; border-radius: 15px; padding: 15px;"></div>
      </div>

    </div>
  </div>

</div>
</div>