config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root is the homepage
  # root is the page devise goes to after logging in
  root 'projects#new'

  get 'analytics/usage', to: 'analytics#usage'
  get 'community/home', to: 'community#home'
  get 'profile', to: 'profiles#show'
  get 'profile/:id', to: 'profiles#show'
  get 'profile/projects', to: 'profiles#load_project_previews'
  get 'analytics/project_location_csv'
  get 'analytics/project_runtimes'
  get 'analytics/users_created'
  get 'users/projects', to: 'users#projects'

  get 'users/projects', to: 'users#projects'
  get 'users/projects/:id', to: 'users#projects'
  get 'users/followers', to: 'users#followers'
  get 'users/following', to: 'users#followees'
  get '/users/newProject', to: 'users#newProjectButton'

  get 'users/index', to: 'users#index'
  get 'users/searchbar', to: 'users#searchbar'
  post 'users/search', to: 'users#search'
  post 'users/follow', to: 'users#follow'
  post 'users/unfollow', to: 'users#unfollow'

  post '/projects/:id/permissions/:visibility', to: 'projects#toggle'
  post '/projects/:id/run', to: 'projects#run'
  get '/projects/:id/progress', to: 'projects#progress'
  get '/projects/:id/cancel', to: 'projects#cancel'

  resources(:projects,  except: [:index]) do
    member do
      post 'receive_service_output', to: 'projects#receive_service_output'
      get 'fork', to: 'projects#fork'
      post '',  to: 'projects#create'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  default_scope { order updated_at: :desc }

  # has_and_belongs_to_many :users
  has_many :project_users
  has_many :users, through: :project_users

  # returns the time that this project was created
  def created_at
    self[:created_at].strftime("%D")
  end

  # sets this project's 'public' attribute to either
  # true or false
  def set_visibility(visibility)
    self.public = visibility
  end

  # creates a project for the user associated with user_id
  # that is an exact copy of this project
  def fork user_id
    user = User.find(user_id)
    project = user.projects.create
    project.title = self.title
    project.eta = self.eta
    project.input = self.input
    project.service_options = self.service_options
    project.save
  end

  # returns the input for this project. This is what will
  # be the input for the SMACK process
  def input
    if self.id == nil
      return nil
    end

    input_path = Rails.root.join('public', 'system', 'projects', 'input', self.id.to_s)
    if(File.file?(input_path))
      file = File.open(input_path)
      input = file.read
      file.close
      return input
    else
      return nil
    end
  end

  # Sets the input for this project
  # MUST FIRST SAVE PROJECT BEFORE CALLING THIS SO THE ID IS POPULATED
  def input=(value)
    if value == nil
      return nil
    end

    # Need to make sure a save is done before writing to file so we know the id.
    if self.id == nil
      self.save
    end

    file = File.open(Rails.root.join('public', 'system', 'projects', 'input', self.id.to_s), 'w')
    file.write(value)
    file.close
  end

  # returns the output given by the SMACK process for this project.
  # if a SMACK process has yet to be executed, the output is nil
  # if there is a SMACK process currently running for this project,
  # then the output is 'pending'
  def output
    if self.id == nil
      return nil
    end

    output_path = Rails.root.join('public', 'system', 'projects', 'output', self.id.to_s)

    # If the file exists, return the file's contents
    if(File.file?(output_path))
      file = File.open(output_path)
      output = file.read
      file.close
    else # Otherwise, the job is still processing
      output = nil
    end

    return output
  end

  # Sets the output for this project
  def output=(value)
    # If there is no ID associated with the project, create one by saving the project.
    if self.id == nil
      self.save
    end

    output_path = Rails.root.join('public', 'system', 'projects', 'output', self.id.to_s)
    # Delete the output file if value is nil
    if value == nil
      File.delete(output_path) if File.exist?(output_path)
      return nil
    else # Otherwise write the output value to file
      file = File.open(output_path, 'w')
      file.write(formatOutput(value))
      file.close
    end
  end

  def ajax_json
    (self.to_json only: [:eta, :output, :id]).html_safe
  end

  def formatOutput(output)
    formatted = ''
    output.each_line do |line|
      formatted += line.gsub(/\/home\/ubuntu\/src\/smack_server\/public\/system\/projects\/[0-9]+\//, '');
    end
    return formatted;
  end

  # returns the id of the user that owns this project
  def owner
    ProjectUser.where(project_id: self.id).first.user_id
  end

  # Returns the time-to-completion progress for the SMACK process associated with this project as a decimal.
  # When the progress is 1, the process for this project is completed.
  def progress
    if self.eta = 0
      return 1
    end
    time_elapsed = ((DateTime.now - self.time_started.to_datetime) * 24 * 60 * 60).to_f
    progress = (time_elapsed / self.eta.to_f).to_f
    progress
  end
end

app/controllers/projects_controller.rb
require 'csv'
require 'json'
require 'digest/md5'

class ProjectsController < ApplicationController
  #protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json'}
  before_action :set_project, only: [:show, :edit, :update, :receive_service_output]

  # Production SMACK server URL
  #SERVICE_REQUEST_HOST = ENV['SMACK_SERVER_HOST']
  SERVICE_REQUEST_HOST = "ec2-52-53-187-90.us-west-1.compute.amazonaws.com:3000"
  PROJECT_CSV_PATH = Rails.root.join('public', 'assets', 'ProjectLocations.csv')
  RUNTIME_THRESHOLD = 500; # Ignore projects with runtimes more than this number when calculating average runtimes for eta.

  Geocoder.configure(:timeout => 10000)

  # GET /projects/1
  # GET /projects/1.json
  def show
    respond_to do |format|
      format.json
    end
  end

  def fork
    Project.find(params[:id]).fork(current_user.id)
  end

  # GET /projects/new
  # Displays the initial code editor to the user.
  def new
    if current_user == nil
      @project = Project.new
      return
    end
    @project = current_user.projects.new
  end

  # POST /projects.json
  # Creates a new project, makes a request to the SMACK server,
  # and saves the input to the file system as a Base64 string.
  def create
    puts project_params.to_h
    if current_user == nil
      @project = Project.new( project_params )
    else
      @project = current_user.projects.create project_params
      @project.save
    end

    @project.input = params[:project][:input]

    # Need to save before send_service_input in order to know the project id
    # current_user.projects.push @project if current_user
    if params[:run]

      @project[:service_options] = generateOptionsString('smack-options.json')
      op_hash = generateMD5ForImportantOptions('smack-options.json')
      @project[:options_hash] = op_hash
      @project.input = params[:project][:input] # Save the input
      send_service_input # Make a request to the SMACK server with the new project


      avg =  Project.where('options_hash = ? and runtime <= ?', op_hash, RUNTIME_THRESHOLD).average('runtime');
      if(avg != nil)
        @project[:eta] = (avg == 0) ? 1 : avg; #if it is expected to run for 0 seconds make the eta 1 second
      else
        avg = Project.where('runtime <= ?', RUNTIME_THRESHOLD).average('runtime');
        @project[:eta] = (avg == 0) ? 1 : avg;
      end
    end

    # Save the new project to the database and redirect the user to 'edit'
    respond_to do |format|
      puts "which format"
      if @project.save
        format.html { redirect_to edit_project_path(@project)}
        format.js
        format.json { render json: @project, only: [:eta, :output, :id] }
      else
        format.any(:js, :json) do
          render json: @project.errors, status: :unprocessable_entity
        end
        format.html { render :new }
      end
    end
    updateCSV
  end

  # GET /projects/1/edit
  # Displays an already existing project to the user.
  def edit
    @base64_input = @project.input
    @output = @project.output
  end

  # PATCH/PUT /projects/1
  # Updates the project db attributes, saves the new input to the file system,
  # deletes the old output from file system.
  def update
    # Delete the old output so the client doesn't get confused thinking it is the new output.
    @project.output = nil

    @project.input = params[:project][:input]
    @project[:service_options] = generateOptionsString('smack-options.json')

    if params[:run]
      send_service_input # Make a request to the SMACK server with updated project
      op_hash = generateMD5ForImportantOptions('smack-options.json')
      @project[:options_hash] = op_hash
      avg =  Project.where('options_hash = ? and runtime <= ?', op_hash, RUNTIME_THRESHOLD).average('runtime');
      if(avg != nil)
        @project[:eta] = (avg == 0) ? 1 : avg; #if it is expected to run for 0 seconds make the eta 1 second
      else
        avg = Project.where('runtime <= ?', RUNTIME_THRESHOLD).average('runtime');
        @project[:eta] = (avg == 0) ? 1 : avg;
      end
    end

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to edit_project_path(@project)}
        format.js {}
        format.json { render json: @project, only: [:eta, :output, :id] }
      else
        format.any(:js, :json) do
          render json: @project.errors, status: :unprocessable_entity
        end
        format.html { render :edit } # If the save fails, show the user the edit window again.
      end
    end
  end

  # GET /projects/1.json will be called every "eta" seconds (AJAX)
  # until there is output associated with the open project.
  def show
    respond_to do |format|
      format.json { render json: @project, only: [:eta, :output, :id] }
    end
  end

  # POST /projects/receive_service_output
  # Called by the SMACK server when a project has finished running.
  # Saves the output to the file_system
  def receive_service_output
    # Get params and associate :output with the project with id :id
    if params[:output] != nil && params[:output] != ''
      @project.output = params[:output]
    else
      @project.output = 'SMACK did not return any output.';
    end

    @project[:runtime] = params[:time_elapsed]
    @project[:eta] = 0
    @project.save
  end

  # DELETE /projects/:id
  def destroy
    if current_user == nil
      Project.find(params[:id].to_i).destroy
    else
      user = User.find(current_user.id.to_i)
      user.projects.destroy(params[:id].to_i)
    end
    puts 'deleted'
    respond_to do |format|
      format.html { render :nothing => true }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def toggle
    owned_project_ids = current_user.projects.map { |proj| proj.id.to_i }
    if owned_project_ids.include? params[:id].to_i
      project = Project.find(params[:id])
      if params[:visibility] == 'public'
        project.public = true
      end
      if params[:visibility] == 'private'
        project.public = false
      end
      project.save
      render json: nil, status: :ok
      return
    end
      render status: :forbidden
  end

  def run
     @project = Project.find(params[:id])
     @project.time_started = DateTime.now
     @project.output = 'pending'
     @project.eta = Project.where('runtime <= ?', RUNTIME_THRESHOLD).average('runtime').to_i
     @project.save
     response = RestClient.post("#{SERVICE_REQUEST_HOST}/job_started",
     {
         :id => @project[:id],
         :options => @project[:service_options],
         :input => @project.input,
         return_port: request.port
     }.to_json, {content_type: :json, accept: :json})
     # Set the project's eta to the SMACK server's predicted processing time
    render partial: 'profiles/running_project', locals: { project: @project }
    # render json: {eta: JSON.parse(response.body)['eta']  }
  end

  def progress
    @project = Project.find(params[:id])
    render json: {progress: @project.progress, output: @project.output}
  end

  def cancel
    @project = Project.find(params[:id])
    @project.output = nil
  end

    private

  # Sends post request to verification service.
  # Returns: eta
  def send_service_input
    # Send the request
    puts "entered send_service_input"
    base64Input = params[:project][:input]
    response = RestClient.post("#{SERVICE_REQUEST_HOST}/job_started",
    {
        id: @project[:id],
        options: @project[:service_options],
        input: base64Input,
        return_port: request.port
    }.to_json, {content_type: :json, accept: :json})
    # Set the project's eta to the SMACK server's predicted processing time
    eta = JSON.parse(response.body)['eta']
    puts "send_service_input eta"
    puts eta
    return eta
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    puts params.to_h
    params.require(:project).permit(:title, :input, :public)
  end

  # Looks at the service options config file and creates
  # an options string to be passed to the command-line
  # service.
  def generateOptionsString(optionsConfigFile)
    optionsString = ''
    json = File.read("#{Rails.root}/public/config/" + optionsConfigFile)
    json = JSON.parse(json)

    json['Group Options'].each do |group|
      if params.include? group['name']
        optionsString += '--' + group['name'] + ' ' + params[group['name']] + ' '
      end
    end

    json['Integer Options'].each do |option|
      if params.include? option['name']
        optionsString += '--' + option['name'] + ' ' + params[option['name']] + ' '
      end
    end

    json['String Options'].each do |option|
      if params.include? option['name'] and params[option['name']] != ''
        optionsString += '--' + option['name'] + ' ' + params[option['name']] + ' '
      end
    end

    json['Boolean Options'].each do |option|
      if params.include? option['name']
        optionsString += '--' + option['name'] + ' '
      end
    end
    return optionsString
  end

  # Creates an MD5 checksum hash for the options. This
  # is used to estimate the runtime for projects with the
  # same options.
  # String options have too much variability. The hashed
  # options are integer, group, and boolean options.
  # Ineger options are rounded to the nearest 100 to
  # prevent too much variablility.
  def generateMD5ForImportantOptions(optionsConfigFile)
    options = ''
    json = File.read("#{Rails.root}/public/config/" + optionsConfigFile)
    json = JSON.parse(json)
    json['Group Options'].each do |group|
      if params.include? group['name']
        options += group['name'] + ' ' + params[group['name']] + ' '
      end
    end

    json['Integer Options'].each do |option|
      if params.include? option['name']

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_file_tree_form.html.erb
<%= form_for @project, remote: true, format: :js, html: {id: :file_tree_form} do |f| %>
  <%= f.text_field :input, value: @project.input %>
<% end %>

app/views/projects/_form.html.erb
<div hidden>
  <%= text_area_tag :project_output, @output %>
</div>

<div id="top-row" class="lgray flex-row h-form-row flex-align-center">
  <div class="flex-col-md-2 flex-col-sm-4">
    <%= text_field_tag :title, @project.title, {placeholder: "Title", class: "form-control"} %>
  </div>

  <div id="output-status" class="flex-col-sm-8 flex-col-md-10">
    <label> Status:
    </label>
    <input id="project-status" type="text" value="Not yet verified" class="form-control flex-col-xs-10"/>
  </div>
</div>

<div class="main-container flex-row">
    <!-- Sidebar -->
    <div id="sidebar" class="flex-col-xs-4 flex-col-md-2 gray">
      <!-- Files -->
      <div id="upload-project-container">
        <div class="field white-color">
          <%= link_to "Upload Project", '#', {:class => 'navbar-link', 'data-target' => "#new_project_modal", 'data-toggle' => "modal" }  %>

          <span id="input_upload_status"></span>
        </div>
      </div>

      <div id="file-list">
      </div>
    </div>

    <!-- Main -->
    <div class="flex-col-xs-8 flex-col-md-10">

      <!-- Middle -->
      <div id="editors-row" class="lgray output-shrunk">

        <!-- Left -->
        <div id="input-editor-container" class="editor-container">
          <div id="inputEditor" class="ace-editor"></div>
        </div>

          <div id="collapse-output-btn">
            <span id="collapse-output-text"></span>
          </div>

        <!-- Right -->
        <div id="output-editor-container" class="editor-container">

          <div id="outputEditor" class="ace-editor">
          </div>
        </div>

      </div>

      <!-- Bottom -->
      <%= render "options_and_run_row" %>
    </div>
</div>

</div>

<!-- End page body -->
<script src="/assets/ace/ace.js" type="text/javascript" charset="utf-8">
</script>

app/views/projects/_options_and_run_row.html.erb
<!-- Bottom -->
<div id="options-and-run-row" class="lgray h-form-row flex-row">
  <!-- Bottom Left -->
  <div class="flex-col-sm-9 flex-col-sm-grow flex-col-md-6 flex-col-md-nogrow">
    <%= form_for(@project, remote: true, format: :js, html: {id: "project_form"}) do |f| %>
      <!--Placeholder for options menu-->
      <div class="btn-group" id="optionsMenu">
        <button data-toggle="dropdown" class="btn btn-default btn-primary dropdown-toggle">
          Options
          <span class="caret"></span>
        </button>
      </div>
      <div hidden>
        <%= f.text_field :input, value: @project.input %>
        <%= f.text_field :title %>
        <%= f.radio_button :public, true  %>
        <%= f.radio_button :public, false %>
        <input id=run_flag name=run value=true disabled/>
      </div>
      <%= f.submit "Verify", name: :run, type: :button, id: :run_button,
                   class: "btn btn-default btn-primary run-button" %>
    <% end %>
    <%= form_for @project, remote: true, format: :json, html: {id: "poll-form"} do end%>
  </div>
</div>

<%
  splitOptionsString = [];
  if !@project[:service_options].nil?
    splitOptionsString = @project[:service_options].split()
  end

  # Generate hidden options menu for each config file that will be pulled into
  # the shown options menu when the service type is changed.
  require 'json'
  option_config_files = %w[smack-options.json]
  option_config_files.each do |file|
    json = File.read("#{Rails.root}/public/config/" + file)
    json = JSON.parse(json)
    id = 1%>
      <div class='hidden' id='<%=file[0..file.index('.json')-1]%>'>
        <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"
                data-placeholder='false'>Options <span class="caret"></span></button>
        <ul class="dropdown-menu scrollable-menu pull-top noclose" role="menu">

          <h6 class="dropdown-header">Integer Options</h6>
          <%json['Integer Options'].each do |option|
              index = splitOptionsString.find_index('--'+option['name'])
              if index.nil?
                value = option['default']
              else
                value = splitOptionsString[index + 1]
              end
          %>
              <li><label><%=option['name']%>
                <input type="number" name="<%=option['name']%>" value="<%=value%>" min="<%=option['min']%>"
                       max="<%=option['max']%>" step="1"/></label></li>
            <%id+=1
            end%>

          <h6 class="dropdown-header">String Options</h6>
          <%json['String Options'].each do |option|
              index = splitOptionsString.find_index('--'+option['name'])
              if index.nil?
                value = option['default']
              else
                value = splitOptionsString[index + 1]
              end
          %>
              <li><label><%=option['name']%>
                <input type="text" name="<%=option['name']%>" value="<%=value%>"/></label></li>
          <%id+=1
            end%>

          <h6 class="dropdown-header">Boolean Options</h6>
          <%json['Boolean Options'].each do |option|
              index = splitOptionsString.find_index('--'+option['name'])
              if index.nil?
                checked = ''
              else
                checked = 'checked'
              end
          %>
              <li>
                <input name='<%=option['name']%>' <%=checked%> type='checkbox' id='<%=id%>'/>
                <label for='<%=id%>' ><%=option['name']%></label>
              </li>
          <%
              id+=1
            end
          %>

          <%json['Group Options'].each do |group|
              index = splitOptionsString.find_index('--'+group['name'])
              if !index.nil?
                value = splitOptionsString[index + 1]
              end
          %>
              <h1 class="dropdown-header"><%=group['name']%></h1>
              <%group['options'].each do |option|
                  if (index.nil? and option['default']) or (!index.nil? and option['name'] == value)%>
                        <li><input type="radio" id="<%=id%>" name="<%=group['name']%>" value="<%=option['name']%>" checked >
                          <label for="<%=id%>"><%=option['name']%></label></li>
                    <%else%>
                        <li><input type="radio" id="<%=id%>" name="<%=group['name']%>" value="<%=option['name']%>">
                          <label for="<%=id%>"><%=option['name']%></label></li>
                  <%
                  end
                  id += 1
              end%>
          <%end%>
        </ul>
      </div>
<%end%>

app/views/projects/_project_input_container.html.erb
<div id="project-input-container" hidden>
  <%= form_for(@project, remote: true, format: :js, 
               html: {id: "project-input-form"}) do |f| %>
      <%= f.text_field :input, value: @base64_input%>
  <% end %>
</div>

app/views/projects/create.js.erb
// Replaces the create forms with edit forms
$("#options-and-run-row").replaceWith("<%= j render partial: "options_and_run_row" %>");
console.log("got 1");
$("#file_tree_form").replaceWith("<%= j render partial: "file_tree_form" %>");
console.log("got 2");
$(".selectpicker").selectpicker();
console.log("got 3");
initOptionsMenu();
console.log("got 4");

// Updates the Url
<% prev_url = url_for controller: 'projects', action: 'edit', id: @project.id %>
var stateObj = { prev: "<%= prev_url %>" };
console.log("got 5");
window.history.pushState(stateObj, "<%= @project.title %>", "<%= prev_url %>");
console.log("got 6");
<% if params[:run] %>
  <% poll_url = url_for controller: 'projects', action: :show, id: @project.id, format: :json %>
  RunProjectForm.requestOutputFromServer("<%= poll_url %>");
<% end %>

app/views/projects/edit.html.erb
<div hidden>
  <%= text_area_tag :output, @output %>
</div>

<%= render partial: "project_input_container" %>

<div id="top-row" class="lgray flex-row h-form-row flex-align-center">
  <div class="flex-col-md-2 flex-col-sm-4">
    <%= form_for @project, remote: true, html: {id: 'project-title-form'} do |f| %>
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    <% end %>
  </div>

  <div class="flex-col-md-5 flex-col-md-nogrow flex-col-sm-grow flex-col-sm-6">
    <select class="selectpicker flex-col-xs-12">
      <option>Smack</option>
      <option>Boogie</option>
    </select>
  </div>
  <div class="flex-col-md-1">
    <button class="btn btn-primary tool-select-button">?</button>
  </div>
</div>

<div class="main-container flex-row">
    <!-- Sidebar -->
    <div id="sidebar" class="flex-col-sm-4 flex-col-md-2 gray">
      <!-- Files -->
      <div id="upload-project-container">
        <div class="field white-color">
          <%= label_tag :input_upload, "Upload Project" %>
          <%= file_field_tag :input_upload, accept: ".zip, application/zip", 
                             class: 'white-color' %>
          <span id="input_upload_status"></span>
        </div>
      </div>

      <div id="file-list">
      </div>

    </div>

    <!-- Main -->
    <div class="flex-col-sm-8 flex-col-md-10">

      <!-- Middle -->
      <div id="editors-row" class="flex-row flex-wrap flex-align-stretch lgray">

        <!-- Left -->
        <div class="editor-container flex-col-sm-12 flex-col-md-6">
          <div id="editor1">
          </div>
        </div>

        <!-- Right -->
        <div class="editor-container flex-col-sm-12 flex-col-md-6">
          <div id="editor2">
          </div>
        </div>
      </div>

      <!-- Bottom -->
      <div id="options-and-run-row" class="bottom-container lgray h-form-row flex-row">
        <!-- Bottom Left -->
        <div class="flex-col-sm-9 flex-col-sm-grow flex-col-md-6 flex-col-md-nogrow">
          <select multiple class="flex-col-xs-12 options-select selectpicker" data-live-search="true">
            <option value="volvo">Option 1</option>
            <option value="saab">Option 2</option>
          </select>

        </div>

        <!-- Bottom Right -->
        <div class="col-md-1">
          <% if @project.persisted? %>
            <%= form_for(@project, url: {id: @project.id, action: :run}, remote: true, 
                         html: {id: 'run-project-form'}) do |f| 
            %>
              <%= f.submit(value: "Run", 
                options: {id: :run_project, class: "btn btn-default btn-primary run-button"})
              %>
            <% end %>
          <% else %>
            <div class="tooltip-wrapper run-button " data-toggle="tooltip" data-placement="top"
                 title="Add some code to your project before you try to run it">
              <button class="btn btn-default btn-primary" disabled>
                Run
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>

<div>

<!-- End page body -->

<script src="/assets/ace/ace.js" type="text/javascript" charset="utf-8"></script>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Output</th>
      <th>Eta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.output %></td>
        <td><%= project.eta %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/load_project_into_filetree.js.erb
$('#load_project_into_filetree').html.erb

app/views/projects/new.html.erb
<h1 hidden>New Project</h1>

<%= render 'form', project: @project %>

<!-- <%= link_to 'Back', projects_path %> -->

app/views/projects/run.js.erb
let projectJson = JSON.parse('<%= @project.ajax_json %>');
pollForOutputUpdates(projectJson);

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Output:</strong>
  <%= @project.output %>
</p>

<p>
  <strong>Eta:</strong>
  <%= @project.eta %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/update.js.erb
<% if params[:run] %>
  <% poll_url = url_for controller: 'projects', action: :show, id: @project.id, format: :json %>
  RunProjectForm.requestOutputFromServer("<%= poll_url %>");
<% end %>